-- Create a customers table to store profile data that isn't in sales
create table public.customers (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  name text,
  email text,
  notes text,
  rating decimal(2,1) default 5.0,
  is_vip boolean default false,
  is_banned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.customers enable row level security;

-- Policy: Authenticated users can read/write (Admin only app)
create policy "Allow all access for authenticated users"
on public.customers
for all
using (auth.role() = 'authenticated');
