-- Export customers table (separate from shop customers)
CREATE TABLE IF NOT EXISTS public.export_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT UNIQUE NOT NULL,
    name TEXT,
    email TEXT,
    address TEXT,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.export_customers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access to export_customers" ON public.export_customers;
CREATE POLICY "Allow full access to export_customers"
ON public.export_customers
FOR ALL
USING (true);

-- Export customer transactions (khatabook for export business)
CREATE TABLE IF NOT EXISTS public.export_customer_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    customer_id BIGINT REFERENCES public.export_customers(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('advance', 'udhar', 'withdraw')),
    amount NUMERIC NOT NULL,
    description TEXT,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.export_customer_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access to export_customer_transactions" ON public.export_customer_transactions;
CREATE POLICY "Allow full access to export_customer_transactions"
ON public.export_customer_transactions
FOR ALL
USING (true);
